### ISSUE TITLE
Don't crash on bad commands

### ISSUE THREAD

**Issue by supermitch** [pulseenergy/vacation#14]
For example:

``` bash
(venv) ➜  vacation git:(master) ./run.py days 50
Traceback (most recent call last):
  File "./run.py", line 9, in <module>
    main()
  File "./run.py", line 5, in main
    vacation.main()
  File "/Users/mitch/Dev/python/vacation/vacation/vacation.py", line 20, in main
    transactions.execute(tokens)
  File "/Users/mitch/Dev/python/vacation/vacation/transactions.py", line 22, in execute
    for action, value in tokens:
TypeError: 'NoneType' object is not iterable
```

**Comment by supermitch** [comment]
Fixed (at least superficially) with commit 2a8dd3bcae6c1d03aa039aa206354865290d09b3.
